"""Suite-wide policy: a skipped test is a defect, not a status.

This suite carried 13 permanently-skipped tests for a month. They pinned behaviour
retired 2026-06-24, so they asserted nothing while still reading as coverage — and
three of them no longer even passed when unskipped. That is a broken window: it
hides real regressions and it trains everyone to ignore the summary line.

So an unexpected skip fails the run. If behaviour is retired, delete its tests (git
history keeps the contract). If a skip is genuinely environmental, add its reason
substring to ``ALLOWED_SKIP_REASONS`` with a comment saying why it cannot be an
assertion instead.
"""

from __future__ import annotations

import time

import pytest

from crewborg import nlp

# How long to wait for the spaCy model before giving up and letting the claim tests
# fail loudly. Generous: the cost is paid once per session and only if something is
# wrong, whereas a short bound would reintroduce the flake on a loaded box.
_MODEL_WAIT_SECONDS = 60.0


@pytest.fixture(scope="session", autouse=True)
def _spacy_model_ready() -> None:
    """Block until the claim parser's spaCy model is loaded.

    `strategy/claims.parse_claims` returns `[]` while the model is still loading --
    correct in production, where it must never block the tick loop, but it would make
    every claim-dependent test a race against a background thread. Waiting once per
    session makes the suite deterministic; a genuinely missing model then fails those
    tests on their own assertions rather than silently returning "asserts nothing".
    """

    nlp.ensure_loading()
    deadline = time.monotonic() + _MODEL_WAIT_SECONDS
    while nlp.state() == "loading" and time.monotonic() < deadline:
        time.sleep(0.05)

# Substrings matched against the skip reason. Keep this list short and justified.
ALLOWED_SKIP_REASONS: tuple[str, ...] = (
    # test_navbake.py: the baked nav asset is generated by tools/nav_bake.py and is
    # not vendored in every checkout. Genuinely absent input, not retired behaviour.
    "no vendored navbake asset",
)

_unexpected_skips: list[str] = []


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    if not report.skipped:
        return
    # longrepr for a skip is (path, lineno, "Skipped: <reason>")
    reason = report.longrepr[2] if isinstance(report.longrepr, tuple) else str(report.longrepr)
    if not any(allowed in reason for allowed in ALLOWED_SKIP_REASONS):
        _unexpected_skips.append(f"{item.nodeid}: {reason}")


def pytest_sessionfinish(session, exitstatus):
    if _unexpected_skips and session.exitstatus == 0:
        session.exitstatus = pytest.ExitCode.TESTS_FAILED


def pytest_terminal_summary(terminalreporter):
    if not _unexpected_skips:
        return
    terminalreporter.section("unexpected skips (treated as failures)", red=True)
    for line in _unexpected_skips:
        terminalreporter.write_line(line)
    terminalreporter.write_line(
        "Delete tests for retired behaviour, or justify the skip in "
        "crewborg/tests/conftest.py:ALLOWED_SKIP_REASONS."
    )
